name: Update Client

on:
  push:
    branches:
      - main
    paths:
      - "client/**"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      hash: ${{ steps.git_hash.outputs.hash }}

    steps:
      - uses: actions/checkout@v3

      - name: Get Git Hash
        id: git_hash
        run: |
          HASH=$(git rev-parse --short HEAD)
          echo "hash=$HASH" >> $GITHUB_OUTPUT

      - name: Build client image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/client:${{ steps.git_hash.outputs.hash }} ./client
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/client:${{ steps.git_hash.outputs.hash }}

  deploy:
    needs: build # Run deploy only after the build job succeeds
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY}}
          port: 22
          script: |
            export DOCKER_HUB_USERNAME="${{ secrets.DOCKER_HUB_USERNAME }}"
            export TAG="${{needs.build.outputs.hash }}"
            cd client/
            # Pull the new Docker image and restart the container
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/client:${{needs.build.outputs.hash }}
            docker-compose down
            docker-compose up -d
